package io.bratexsoft.core.designsystem.theme

import androidx.compose.ui.graphics.Color

val mdThemeLightPrimary = Color(0xFF006E25)
val mdThemeLightOnPrimary = Color(0xFFFFFFFF)
val mdThemeLightPrimaryContainer = Color(0xFF78FE87)
val mdThemeLightOnPrimaryContainer = Color(0xFF002106)
val mdThemeLightSecondary = Color(0xFF265EA7)
val mdThemeLightOnSecondary = Color(0xFFFFFFFF)
val mdThemeLightSecondaryContainer = Color(0xFFD6E3FF)
val mdThemeLightOnSecondaryContainer = Color(0xFF001B3D)
val mdThemeLightTertiary = Color(0xFF006686)
val mdThemeLightOnTertiary = Color(0xFFFFFFFF)
val mdThemeLightTertiaryContainer = Color(0xFFC0E8FF)
val mdThemeLightOnTertiaryContainer = Color(0xFF001E2B)
val mdThemeLightError = Color(0xFFBA1A1A)
val mdThemeLightErrorContainer = Color(0xFFFFDAD6)
val mdThemeLightOnError = Color(0xFFFFFFFF)
val mdThemeLightOnErrorContainer = Color(0xFF410002)
val mdThemeLightBackground = Color(0xFFFAFCFF)
val mdThemeLightOnBackground = Color(0xFF001E2B)
val mdThemeLightSurface = Color(0xFFFAFCFF)
val mdThemeLightOnSurface = Color(0xFF001E2B)
val mdThemeLightSurfaceVariant = Color(0xFFDEE5D9)
val mdThemeLightOnSurfaceVariant = Color(0xFF424940)
val mdThemeLightOutline = Color(0xFF72796F)
val mdThemeLightInverseOnSurface = Color(0xFFE1F3FF)
val mdThemeLightInverseSurface = Color(0xFF003547)
val mdThemeLightInversePrimary = Color(0xFF5AE06E)
val mdThemeLightShadow = Color(0xFF000000)
val mdThemeLightSurfaceTint = Color(0xFF006E25)

val mdThemeDarkPrimary = Color(0xFF5AE06E)
val mdThemeDarkOnPrimary = Color(0xFF00390F)
val mdThemeDarkPrimaryContainer = Color(0xFF00531A)
val mdThemeDarkOnPrimaryContainer = Color(0xFF78FE87)
val mdThemeDarkSecondary = Color(0xFFA8C8FF)
val mdThemeDarkOnSecondary = Color(0xFF003062)
val mdThemeDarkSecondaryContainer = Color(0xFF00468A)
val mdThemeDarkOnSecondaryContainer = Color(0xFFD6E3FF)
val mdThemeDarkTertiary = Color(0xFF70D2FF)
val mdThemeDarkOnTertiary = Color(0xFF003547)
val mdThemeDarkTertiaryContainer = Color(0xFF004D66)
val mdThemeDarkOnTertiaryContainer = Color(0xFFC0E8FF)
val mdThemeDarkError = Color(0xFFFFB4AB)
val mdThemeDarkErrorContainer = Color(0xFF93000A)
val mdThemeDarkOnError = Color(0xFF690005)
val mdThemeDarkOnErrorContainer = Color(0xFFFFDAD6)
val mdThemeDarkBackground = Color(0xFF001E2B)
val mdThemeDarkOnBackground = Color(0xFFC0E8FF)
val mdThemeDarkSurface = Color(0xFF001E2B)
val mdThemeDarkOnSurface = Color(0xFFC0E8FF)
val mdThemeDarkSurfaceVariant = Color(0xFF424940)
val mdThemeDarkOnSurfaceVariant = Color(0xFFC2C9BD)
val mdThemeDarkOutline = Color(0xFF8C9388)
val mdThemeDarkInverseOnSurface = Color(0xFF001E2B)
val mdThemeDarkInverseSurface = Color(0xFFC0E8FF)
val mdThemeDarkInversePrimary = Color(0xFF006E25)
val mdThemeDarkShadow = Color(0xFF000000)
val mdThemeDarkSurfaceTint = Color(0xFF5AE06E)


val seed = Color(0xFF2DBA4D)